const horoscopeData = {
  aries: {
    daily: {
      general: 'The cosmos are aligning in your favor today, Aries. Mars, your ruling planet, energizes your spirit with unstoppable drive. New opportunities are presenting themselves — seize them with your characteristic boldness. Trust your instincts, for they rarely lead you astray.',
      love: 'Your magnetic energy attracts admirers today. Single Aries may encounter a spark of connection in unexpected places. For those in relationships, express your feelings openly — your partner longs to hear your heartfelt words.',
      career: 'A bold idea you\'ve been holding back deserves to see the light today. Present your vision with confidence. Colleagues will respond to your enthusiasm. A financial opportunity may also present itself — evaluate it carefully before committing.',
      health: 'High energy levels make today perfect for an intense workout. Channel your physical vitality through cardio or competitive sports. Stay mindful of your head and neck — avoid strain. Proper hydration is key.',
      luckyColor: 'Red',
      luckyNumber: 9,
      luckyStone: 'Ruby',
    },
    weekly: 'This week brings opportunities for leadership and new beginnings. The first half of the week is excellent for starting new projects or making important decisions. By mid-week, a creative breakthrough arrives. The weekend calls for relaxation and connection with loved ones.',
    monthly: 'This month, Aries enters a period of powerful manifestation. Career goals that seemed distant are within reach as your determination reaches new heights. In love, a deeper bond forms through honest communication. Financial matters require careful attention in the third week, but overall prosperity grows.',
  },
  taurus: {
    daily: {
      general: 'Venus blesses you with an especially beautiful day, Taurus. Your eye for beauty and comfort leads you to make life a little more luxurious. Take time to appreciate the sensory pleasures around you — a good meal, beautiful music, or a scenic walk.',
      love: 'Romance blooms in comfortable, familiar settings today. For couples, a cozy evening at home strengthens your bond. Singles may find attraction developing with someone who shares their appreciation for the finer things in life.',
      career: 'Your steady, methodical approach earns recognition today. A project you\'ve been building slowly is ready to show results. Stay focused on quality over speed. Financial planning efforts begin to show promising returns.',
      health: 'Your body craves nourishment today — focus on wholesome, enjoyable meals. Gentle exercise like yoga or a nature walk suits your energy. Take care of your throat and neck with proper hydration.',
      luckyColor: 'Green',
      luckyNumber: 6,
      luckyStone: 'Emerald',
    },
    weekly: 'Financial matters take center stage this week. Your practical wisdom guides excellent money decisions. Mid-week brings creative inspiration — don\'t dismiss unconventional ideas. Relationships deepen as you share your true feelings. The weekend offers sensory pleasures and peaceful relaxation.',
    monthly: 'This month favors financial growth and creative expression for Taurus. A significant purchase or investment decision requires careful thought in the first two weeks. By month\'s end, your patience rewards you with tangible results. Love life blossoms as Venus enhances your natural charm.',
  },
  gemini: {
    daily: {
      general: 'Your mind sparkles with brilliant ideas today, Gemini. Mercury fuels your communication gifts, making you the most captivating conversationalist in any room. Perfect day for writing, networking, or learning something new that catches your restless intellect.',
      love: 'Witty exchanges lead to deeper connections today. Your charm is irresistible, drawing people to your magnetic personality. An interesting conversation may evolve into something more meaningful. Tell someone special what you genuinely admire about them.',
      career: 'Multi-tasking is your superpower today. Handle several projects simultaneously with ease. A networking opportunity shouldn\'t be missed — important connections are made through casual conversation. Your words carry extra persuasive power now.',
      health: 'Your nervous energy needs productive outlets today. Short, varied exercise sessions work better than long routines. Practice breathing exercises to calm mental chatter. Limit caffeine and prioritize quality sleep tonight.',
      luckyColor: 'Yellow',
      luckyNumber: 5,
      luckyStone: 'Agate',
    },
    weekly: 'Communication breakthroughs define this week. Important messages arrive that shift your perspective on a key situation. Social engagements multiply mid-week — select the most meaningful ones. A sibling or close friend brings news worth celebrating. Travel plans may take shape by the weekend.',
    monthly: 'This month, Gemini\'s intellectual gifts shine brightly. A writing, speaking, or teaching opportunity emerges that aligns perfectly with your talents. Relationships benefit from your improved ability to express deep feelings. Financial decisions require extra research — consult experts before major commitments.',
  },
  cancer: {
    daily: {
      general: 'The Moon amplifies your intuitive gifts today, Cancer. Your emotional intelligence guides you to exactly where you need to be. Home and family matters bring deep satisfaction. Trust those gut feelings — they\'re delivering cosmic messages meant specifically for you.',
      love: 'Deep emotional connections are highlighted today. Your nurturing energy draws those who need comfort. In relationships, your partner feels especially seen and cherished by your attentiveness. Create a special moment at home for those you love.',
      career: 'Your intuitive business sense proves invaluable today. A situation that seemed confusing becomes clear through your emotional intelligence. Collaboration with trusted colleagues yields excellent results. Your ability to understand what clients truly need sets you apart.',
      health: 'Emotional wellbeing directly affects your physical health today. Engage in activities that bring you joy and comfort. Nourish yourself with your favorite wholesome foods. A bath with calming essential oils will restore your energy.',
      luckyColor: 'Silver',
      luckyNumber: 7,
      luckyStone: 'Pearl',
    },
    weekly: 'Family connections are in focus this week. A home-related matter requires your attention but brings lasting benefits. Your nurturing gifts are called upon mid-week — your support makes an enormous difference in someone\'s life. Financially, protect what you\'ve already built rather than risking new ventures.',
    monthly: 'Cancer experiences powerful emotional transformation this month. Old wounds have an opportunity to heal as you embrace vulnerability. Career recognition arrives for your behind-the-scenes efforts. Home improvements or changes to your living situation bring lasting happiness. Your intuition reaches extraordinary levels.',
  },
  leo: {
    daily: {
      general: 'Your star shines brilliantly today, Leo. The Sun, your ruler, infuses you with radiant confidence that lights up every room you enter. This is your time to shine, to lead, and to inspire. Others are naturally drawn to your warmth and charismatic energy.',
      love: 'Your romantic gestures make a powerful impression today. Grand expressions of love — unexpected gifts, heartfelt compliments, or a special outing — create memorable moments. Your partner or potential love interest is captivated by your radiant energy.',
      career: 'Leadership opportunities present themselves today. Step forward with confidence — your natural authority commands respect. Creative projects receive special cosmic support. Public speaking or presentations go exceptionally well under today\'s stellar influences.',
      health: 'Vitality runs high today. Your heart — both literally and symbolically — is strong and full. Channel this energy into vigorous exercise. Back stretches and spine care deserve attention. Your generous spirit benefits from finding balance between giving and receiving.',
      luckyColor: 'Gold',
      luckyNumber: 1,
      luckyStone: 'Amber',
    },
    weekly: 'Recognition and admiration flow your way this week. A creative project reaches its peak performance. Mid-week brings a social opportunity that elevates your status. In love, passionate feelings are rekindled or deepened. Financial rewards for past efforts arrive, bringing well-deserved satisfaction.',
    monthly: 'This month, Leo basks in exceptional cosmic favor. Career advancement brings the recognition you\'ve long deserved. Creative endeavors reach new heights of expression and impact. Romance is intensely passionate — existing relationships deepen, and singles may meet someone extraordinary. Your natural generosity inspires those around you.',
  },
  virgo: {
    daily: {
      general: 'Your analytical mind operates at peak precision today, Virgo. Mercury sharpens your already considerable intellectual gifts. Problem-solving comes easily, and your attention to detail catches what others miss. Your helpfulness and service to others brings deep personal satisfaction.',
      love: 'Small acts of service express your love more powerfully than grand gestures today. Your partner deeply appreciates the care you put into the details of daily life. Singles may find attraction developing with someone who shares their high standards and values.',
      career: 'Your meticulous work pays off as a project you\'ve been refining reaches completion. Colleagues turn to you for guidance, recognizing your expertise. A practical solution to a longstanding problem earns professional recognition. Finances benefit from your careful management.',
      health: 'Your digestive system calls for extra attention today. Eat slowly, choose wholesome foods, and avoid stress-eating. A mindful walk in nature helps clear mental clutter. Journaling tonight releases tensions you\'ve been carrying.',
      luckyColor: 'Navy Blue',
      luckyNumber: 5,
      luckyStone: 'Sapphire',
    },
    weekly: 'Work efficiency reaches new heights this week. A complex project comes together perfectly through your systematic approach. Health and wellness improvements bring noticeable benefits by mid-week. A colleague proves to be a valuable ally. The weekend calls for rest — honor your body\'s need for recovery.',
    monthly: 'Virgo experiences significant professional advancement this month. Your expert skills are recognized and rewarded in concrete ways. Health routines established now create lasting benefits. Relationships benefit from your improved ability to express needs without criticism. Financial planning efforts yield impressive long-term results.',
  },
  libra: {
    daily: {
      general: 'Balance and beauty define your day, Libra. Venus, your ruling planet, enhances your natural grace and charm. Your diplomatic skills resolve a situation that has been creating tension. Social interactions are especially rewarding, bringing connections that lighten your spirit.',
      love: 'Your romantic side flourishes today. Planning something beautiful — a candlelit dinner, art museum visit, or sunset walk — creates the magical atmosphere you and your partner crave. Singles attract admirers with effortless grace.',
      career: 'Your mediating skills are needed and appreciated today. A fair solution to a workplace conflict earns lasting respect. Aesthetic projects or creative work receives special cosmic support. Partnerships and collaborations yield their best results under today\'s influences.',
      health: 'Your kidneys and lower back benefit from extra care today. Stay well hydrated and take breaks to stretch if sitting for long periods. Balance activity with rest. A brief meditation at day\'s end restores your equilibrium.',
      luckyColor: 'Pink',
      luckyNumber: 6,
      luckyStone: 'Rose Quartz',
    },
    weekly: 'Relationships of all kinds are highlighted this week. A partnership — personal or professional — reaches an important turning point requiring honest communication. Mid-week\'s social events bring valuable connections. The pursuit of beauty and harmony in your environment brings surprising joy. Legal matters resolve in your favor.',
    monthly: 'This month, Libra finds the balance they\'ve been seeking. Personal relationships transform as you set healthy boundaries while remaining your naturally giving self. Career partnerships bring exciting new opportunities. Creative projects receive unexpected recognition. Financial decisions made with care now build lasting security.',
  },
  scorpio: {
    daily: {
      general: 'Pluto intensifies your already powerful energy today, Scorpio. You see clearly through illusions, perceiving the hidden truth in every situation. This is an excellent day for research, investigation, or any matter requiring depth of perception. Your personal magnetism is at its peak.',
      love: 'Deep, transformative connections are activated today. Vulnerable honesty with your partner creates profound intimacy. Singles sense the authenticity of potential partners immediately — trust that radar. Avoid power struggles by choosing trust over control.',
      career: 'Your strategic mind uncovers a hidden opportunity that others have overlooked. Financial acumen is especially sharp — now is an excellent time for investment research. A position of greater authority becomes available. Your investigative talents lead to a valuable breakthrough.',
      health: 'Detoxification practices benefit you especially today. Clean eating, adequate water, and reduction of toxins support your body\'s natural regenerative processes. Emotional releases through exercise or creative expression maintain your psychological health.',
      luckyColor: 'Deep Red',
      luckyNumber: 8,
      luckyStone: 'Obsidian',
    },
    weekly: 'Transformation is the theme of this week. Something ends so something better can begin. Your penetrating insight reveals a truth that changes your direction beneficially. Mid-week brings financial opportunities worth investigating. Intimate relationships deepen through courageous honesty.',
    monthly: 'Scorpio experiences profound metamorphosis this month. A major life chapter concludes, making way for extraordinary new beginnings. Career power increases as your strategic brilliance is recognized by the right people. In love, bonds deepen to soul-level intensity. Financial transformation brings lasting improvement to your material circumstances.',
  },
  sagittarius: {
    daily: {
      general: 'Jupiter expands your horizons today, Sagittarius. Adventure calls and your philosophical mind is illuminated with insight. Travel opportunities, higher learning, or bold new experiences beckon. Your optimism is contagious, lifting the spirits of everyone you encounter today.',
      love: 'Your adventurous spirit attracts a fellow explorer of life today. Spontaneous romantic plans create the most magical moments — suggest something unexpected and exciting. Your humor and wisdom make you irresistibly appealing to potential partners.',
      career: 'Thinking big pays off today. A project with international scope or broader reach than usual comes across your path. Your enthusiasm convinces skeptics. Educational pursuits directly advance your career. Publishing, teaching, or sharing your expertise opens important doors.',
      health: 'Your hips and thighs benefit from active movement today. Running, hiking, or dancing suits your adventurous energy. Fresh air and natural settings restore your spirit. Mind expansion through reading or podcast listening nourishes your mental health.',
      luckyColor: 'Purple',
      luckyNumber: 3,
      luckyStone: 'Turquoise',
    },
    weekly: 'Adventure and expansion define this week. A travel opportunity arises that broadens your perspective significantly. Mid-week brings philosophical insights that guide important life decisions. Your natural optimism inspires others to dream bigger. Financial luck accompanies your bold moves.',
    monthly: 'This month, Sagittarius leaps toward their highest aspirations. A journey — literal or metaphorical — expands your understanding of what\'s possible. Career opportunities in international or educational fields arrive at the perfect moment. Relationships with people from different backgrounds enrich your worldview. Philosophical clarity guides your most important decisions.',
  },
  capricorn: {
    daily: {
      general: 'Saturn lends extra discipline and focus to your already determined spirit, Capricorn. Long-term goals crystallize as practical steps become clear. Your reputation continues to grow through consistent excellence. Authority figures take special notice of your professional contributions today.',
      love: 'Your steady, reliable love expresses itself beautifully today. Show vulnerability with your partner — your tender side strengthens the bond. Singles attract admirable partners by simply being their authentic, accomplished selves.',
      career: 'Career advancement is strongly supported today. A meeting with a superior or important client goes exceptionally well. Long-term financial planning bears fruit. Your ability to build lasting structures — in business and beyond — is recognized.',
      health: 'Your bones and joints benefit from moderate, consistent exercise today. Weight-bearing activities strengthen your skeletal structure. Avoid overwork — your ambitious nature sometimes forgets to rest. A massage or hot bath eases physical tension.',
      luckyColor: 'Brown',
      luckyNumber: 4,
      luckyStone: 'Garnet',
    },
    weekly: 'Professional achievements are highlighted all week. A leadership role suits you perfectly — step into it with quiet confidence. Mid-week\'s financial review reveals you\'re on track for your long-term goals. Family matters require balance with career demands. The weekend rewards your hard work with genuine relaxation.',
    monthly: 'Capricorn reaches a significant career milestone this month. Years of disciplined effort culminate in recognition that elevates your status. Financial goals are achieved ahead of schedule through your exceptional planning. Personal relationships deepen as you allow your emotional walls to lower. Your legacy is being built exactly as you envisioned.',
  },
  aquarius: {
    daily: {
      general: 'Uranus sparks revolutionary thinking today, Aquarius. Your innovative ideas have the power to change things for the better — don\'t hold back. Humanitarian causes call for your unique perspective and action. Your authentic individuality inspires others to embrace their own originality.',
      love: 'Intellectual connection leads to romantic chemistry today. A stimulating conversation becomes the foundation of genuine attraction. In relationships, respecting each other\'s individuality strengthens your bond. Plan something unconventional — your unique approach to romance is your greatest gift.',
      career: 'Your visionary thinking solves a problem that conventional approaches couldn\'t crack. Technology and innovation are your allies today. Collaborative work with like-minded people produces exciting breakthroughs. A humanitarian aspect of your work deserves more attention and resources.',
      health: 'Your circulatory system benefits from active movement today. Dance, cycling, or vigorous walking gets blood flowing. Social exercise — team sports or group fitness — suits your collaborative nature. Creative outlets are as important as physical ones for your wellbeing.',
      luckyColor: 'Electric Blue',
      luckyNumber: 11,
      luckyStone: 'Amethyst',
    },
    weekly: 'Revolutionary changes arrive this week, and you embrace them with characteristic enthusiasm. A technological or social innovation project gains momentum. Mid-week connections with progressive, like-minded people inspire new directions. Friendships and community involvement bring deep satisfaction. Financial independence grows through your unique approach.',
    monthly: 'This month, Aquarius\'s vision for the future gains powerful momentum. A project that could genuinely benefit many people reaches a breakthrough stage. Social networks expand to include highly influential, forward-thinking individuals. Personal freedom and authentic self-expression reach new heights. Financial creativity yields unexpected abundance.',
  },
  pisces: {
    daily: {
      general: 'Neptune bathes you in divine inspiration today, Pisces. Your creative and spiritual gifts are especially powerful now. Dreams and visions carry important messages — write them down. Your compassionate presence is exactly what someone nearby needs today.',
      love: 'Your romantic nature creates magical moments effortlessly today. Sharing a creative or spiritual experience with your partner deepens your soul connection. Singles follow their intuition toward a meeting that feels destined. Your emotional openness invites genuine intimacy.',
      career: 'Creative and intuitive approaches outperform analytical ones today. Trust your inspired hunches on a project decision. Artistic work receives enthusiastic appreciation. Helping a colleague through their challenge earns lasting loyalty and advances your own cause.',
      health: 'Your sensitive energy system needs gentle care today. Avoid harsh, overwhelming environments when possible. Time near water — ocean, lake, or even a long bath — restores your spirit. Protect your feet with comfortable, supportive footwear.',
      luckyColor: 'Sea Green',
      luckyNumber: 7,
      luckyStone: 'Aquamarine',
    },
    weekly: 'Spiritual and creative currents run deep this week. An artistic breakthrough arrives mid-week that expresses your soul\'s truest voice. Compassionate service to others brings unexpected personal rewards. Dreams and intuition provide guidance on an important decision. Finances benefit from your instinctive rather than analytical approach.',
    monthly: 'Pisces experiences a profoundly spiritual and creative month. Your artistic gifts find their most powerful expression yet. A compassionate project or healing work takes on greater significance and impact. Intuitive guidance leads to major life improvements in career and relationships. Your sensitivity, once a challenge, becomes your greatest superpower.',
  },
}

export const getHoroscope = (slug) => horoscopeData[slug] || null
export default horoscopeData
