const zodiacData = {
  aries: {
    name: 'Aries',
    slug: 'aries',
    symbol: '♈',
    emoji: '🐏',
    dates: { tropical: 'March 21 – April 19', sidereal: 'April 15 – May 15' },
    element: 'Fire',
    planet: 'Mars',
    quality: 'Cardinal',
    color: '#FF4500',
    stone: 'Diamond',
    luckyNumbers: [1, 9, 19],
    luckyDay: 'Tuesday',
    compatibility: ['leo', 'sagittarius', 'gemini', 'aquarius'],
    traits: {
      positive: ['Courageous', 'Determined', 'Confident', 'Enthusiastic', 'Optimistic', 'Honest', 'Passionate'],
      negative: ['Impatient', 'Moody', 'Short-tempered', 'Impulsive', 'Aggressive'],
    },
    description: 'Aries is the first sign of the zodiac, and that\'s quite fitting for this ram. Aries loves to be number one, so it\'s no surprise that these audacious rams are the first sign of the zodiac. Bold and ambitious, Aries dives headfirst into even the most challenging situations. Like their celestial spirit animal, Aries is the master of the cosmic battlefield. Their fiery personality burns bright, lighting up any room they enter.',
    love: 'In love, Aries is a passionate and devoted partner who craves excitement. They fall hard and fast, bringing intense energy to relationships. They need a partner who can match their enthusiasm and keep up with their adventurous spirit. Aries shows love through bold gestures, spontaneous adventures, and fierce loyalty.',
    career: 'Aries thrives in leadership positions and competitive environments. Natural-born leaders, they excel as entrepreneurs, military officers, athletes, and surgeons. Their drive and ambition push them to the top, though they may clash with authority figures. Best in roles where they can pioneer new ideas.',
    health: 'Aries rules the head and face. They are prone to headaches, migraines, and facial injuries due to their impulsive nature. Regular physical activity is essential to burn off their abundant energy. They should watch for stress-related conditions and practice mindfulness to balance their fiery temperament.',
  },
  taurus: {
    name: 'Taurus',
    slug: 'taurus',
    symbol: '♉',
    emoji: '🐂',
    dates: { tropical: 'April 20 – May 20', sidereal: 'May 16 – June 15' },
    element: 'Earth',
    planet: 'Venus',
    quality: 'Fixed',
    color: '#228B22',
    stone: 'Emerald',
    luckyNumbers: [2, 6, 9],
    luckyDay: 'Friday',
    compatibility: ['virgo', 'capricorn', 'cancer', 'pisces'],
    traits: {
      positive: ['Reliable', 'Patient', 'Practical', 'Devoted', 'Responsible', 'Stable', 'Sensual'],
      negative: ['Stubborn', 'Possessive', 'Uncompromising', 'Materialistic', 'Self-indulgent'],
    },
    description: 'Taurus is an earth sign represented by the bull. Like their celestial spirit animal, Taureans enjoy relaxing in serene, bucolic environments, surrounded by soft sounds, soothing aromas, and sumptuous flavors. Venus, the enchanting planet that governs love, beauty, and money, rules Taurus. Taureans are known for their down-to-earth nature and strong connection to the physical world.',
    love: 'In love, Taurus is loyal, sensual, and deeply devoted. They take their time before committing but once they do, they are in it for life. They express love through physical affection, cooking meals, and creating a comfortable home. They need security and consistency in relationships and are most compatible with partners who share their desire for stability.',
    career: 'Taurus excels in careers that require patience, persistence, and attention to detail. They make excellent bankers, accountants, artists, musicians, and chefs. Their practical nature and reliability make them valued employees. They prefer stable careers with good financial compensation and dislike sudden changes.',
    health: 'Taurus rules the neck, throat, and thyroid gland. They may be prone to throat infections, neck stiffness, and thyroid problems. Regular outdoor activities help ground their earthy energy. They should be mindful of overindulgence in food and comfort, which can lead to weight issues.',
  },
  gemini: {
    name: 'Gemini',
    slug: 'gemini',
    symbol: '♊',
    emoji: '👯',
    dates: { tropical: 'May 21 – June 20', sidereal: 'June 16 – July 15' },
    element: 'Air',
    planet: 'Mercury',
    quality: 'Mutable',
    color: '#FFD700',
    stone: 'Pearl',
    luckyNumbers: [3, 5, 12],
    luckyDay: 'Wednesday',
    compatibility: ['libra', 'aquarius', 'aries', 'leo'],
    traits: {
      positive: ['Gentle', 'Affectionate', 'Curious', 'Adaptable', 'Quick-witted', 'Communicative', 'Versatile'],
      negative: ['Nervous', 'Inconsistent', 'Indecisive', 'Superficial', 'Nosy'],
    },
    description: 'Gemini is represented by the twins Castor and Pollux, known for being social, communicative, and quick-witted. This sign is ruled by Mercury, the planet of communication, giving Geminis their gift of gab. They are intellectually curious and have a wide range of interests. Geminis are known for their duality — able to see all sides of any situation.',
    love: 'In love, Gemini is playful, witty, and intellectually stimulating. They need mental connection as much as physical attraction. Variety and intellectual stimulation are key to keeping a Gemini interested. They are flirtatious by nature but deeply loyal once committed. Communication is paramount in their relationships.',
    career: 'Gemini thrives in careers that involve communication, travel, and variety. They make excellent journalists, teachers, translators, sales representatives, and writers. Their adaptability makes them versatile in many fields. They prefer dynamic work environments over routine-based jobs.',
    health: 'Gemini rules the arms, hands, lungs, and nervous system. They may be prone to respiratory issues, anxiety, and nervous tension. Regular breathing exercises and yoga help calm their restless minds. Keeping a consistent sleep schedule is important for their wellbeing.',
  },
  cancer: {
    name: 'Cancer',
    slug: 'cancer',
    symbol: '♋',
    emoji: '🦀',
    dates: { tropical: 'June 21 – July 22', sidereal: 'July 16 – August 15' },
    element: 'Water',
    planet: 'Moon',
    quality: 'Cardinal',
    color: '#C0C0C0',
    stone: 'Ruby',
    luckyNumbers: [2, 3, 15],
    luckyDay: 'Monday',
    compatibility: ['scorpio', 'pisces', 'taurus', 'virgo'],
    traits: {
      positive: ['Tenacious', 'Highly imaginative', 'Loyal', 'Emotional', 'Sympathetic', 'Persuasive', 'Nurturing'],
      negative: ['Moody', 'Pessimistic', 'Suspicious', 'Manipulative', 'Insecure'],
    },
    description: 'Cancer is a cardinal water sign represented by the crab. Like the tides of the ocean, Cancers are deeply intuitive and sentimental. Ruled by the Moon, they are closely connected to emotions, family, and home. They have an extraordinary capacity for empathy and can sense the emotional needs of those around them. Their nurturing spirit makes them wonderful caretakers.',
    love: 'Cancer in love is deeply devoted, nurturing, and emotionally intense. They create beautiful, comfortable homes and express love through acts of care. They can be clingy and need reassurance of their partner\'s feelings. Highly romantic, they value deep emotional bonds and long-term commitment above fleeting passion.',
    career: 'Cancer excels in careers where they can care for others. They make exceptional nurses, social workers, teachers, chefs, and psychologists. Their strong intuition helps in business decisions. They prefer working in stable environments and excel in family businesses. They are excellent money managers.',
    health: 'Cancer rules the chest, breasts, and stomach. They may be prone to digestive issues, particularly when stressed. Emotional health directly impacts their physical wellbeing. They benefit from meditation and time near water. Creating a peaceful home environment is essential for their overall health.',
  },
  leo: {
    name: 'Leo',
    slug: 'leo',
    symbol: '♌',
    emoji: '🦁',
    dates: { tropical: 'July 23 – August 22', sidereal: 'August 16 – September 15' },
    element: 'Fire',
    planet: 'Sun',
    quality: 'Fixed',
    color: '#FF8C00',
    stone: 'Peridot',
    luckyNumbers: [1, 10, 19],
    luckyDay: 'Sunday',
    compatibility: ['aries', 'sagittarius', 'gemini', 'libra'],
    traits: {
      positive: ['Creative', 'Passionate', 'Generous', 'Warm-hearted', 'Cheerful', 'Humorous', 'Charismatic'],
      negative: ['Arrogant', 'Stubborn', 'Self-centered', 'Lazy', 'Inflexible'],
    },
    description: 'Leo is a fixed fire sign ruled by the Sun. The lion of the zodiac, Leos are natural born leaders who love the spotlight. They are dramatic, creative, and confident, with an unmistakable regal presence. Their warm heart and generosity make them beloved by those around them. Leos are fiercely loyal to their pride and will defend their loved ones with great courage.',
    love: 'In love, Leo is passionate, dramatic, and fiercely loyal. They love grand romantic gestures and adore being adored. They need a partner who appreciates their generous spirit and matches their enthusiasm. Leos are warm and loving partners who shower their significant other with affection and attention.',
    career: 'Leo shines in creative and leadership roles. They excel as actors, directors, CEOs, politicians, and entertainers. They need careers that offer recognition and allow them to express their creativity. They are natural motivators who inspire those around them. Self-employment often suits their independent nature.',
    health: 'Leo rules the heart and spine. They may be prone to heart-related issues and back problems. Regular cardiovascular exercise is beneficial. They should be mindful of stress, which can affect their heart. Maintaining a balanced diet and regular medical check-ups are important for Leo\'s long-term health.',
  },
  virgo: {
    name: 'Virgo',
    slug: 'virgo',
    symbol: '♍',
    emoji: '👧',
    dates: { tropical: 'August 23 – September 22', sidereal: 'September 16 – October 15' },
    element: 'Earth',
    planet: 'Mercury',
    quality: 'Mutable',
    color: '#808000',
    stone: 'Sapphire',
    luckyNumbers: [3, 6, 15],
    luckyDay: 'Wednesday',
    compatibility: ['taurus', 'capricorn', 'cancer', 'scorpio'],
    traits: {
      positive: ['Loyal', 'Analytical', 'Kind', 'Hardworking', 'Practical', 'Meticulous', 'Reliable'],
      negative: ['Shyness', 'Worry', 'Overly critical', 'All work no play', 'Perfectionist'],
    },
    description: 'Virgo is an earth sign historically represented by the goddess of wheat and agriculture. This association speaks to Virgo\'s deep-rooted presence in the material world. Ruled by Mercury, the planet of communication, Virgos have an exceptional analytical mind. They are methodical, practical, and precise, always in pursuit of perfection in everything they do.',
    love: 'In love, Virgo shows affection through acts of service rather than grand gestures. They are devoted partners who pay attention to their loved one\'s needs. They need to feel intellectually respected. Once they trust someone, they are incredibly loyal and caring. They seek stable, long-term relationships over casual flings.',
    career: 'Virgo excels in detail-oriented work. They make excellent scientists, writers, accountants, veterinarians, and healthcare workers. Their analytical minds and attention to detail make them invaluable in any workplace. They are hardworking and dedicated professionals who always strive for excellence.',
    health: 'Virgo rules the digestive system and intestines. They may be prone to digestive disorders, particularly when stressed. Their perfectionist nature can lead to anxiety. Regular exercise, clean eating, and mindfulness practices help maintain their health. They benefit from nature walks and grounding activities.',
  },
  libra: {
    name: 'Libra',
    slug: 'libra',
    symbol: '♎',
    emoji: '⚖️',
    dates: { tropical: 'September 23 – October 22', sidereal: 'October 16 – November 15' },
    element: 'Air',
    planet: 'Venus',
    quality: 'Cardinal',
    color: '#FFB6C1',
    stone: 'Opal',
    luckyNumbers: [4, 6, 13],
    luckyDay: 'Friday',
    compatibility: ['gemini', 'aquarius', 'leo', 'sagittarius'],
    traits: {
      positive: ['Cooperative', 'Diplomatic', 'Gracious', 'Fair-minded', 'Social', 'Charming', 'Idealistic'],
      negative: ['Indecisive', 'Avoids confrontations', 'Will carry a grudge', 'Self-pity', 'Superficial'],
    },
    description: 'Libra is an air sign represented by the scales, a symbol of balance and justice. Ruled by Venus, Libra is the most aesthetically refined of all the signs. They are natural diplomats, always seeking harmony and fairness in all situations. Librans have a strong sense of justice and are deeply troubled by inequality. Their charm and social grace make them beloved by many.',
    love: 'In love, Libra is romantic, charming, and deeply committed to partnership. They are natural romantics who believe in soulmates and true love. They need balance and harmony in their relationships and will go to great lengths to avoid conflict. They make thoughtful, attentive partners who always consider their significant other\'s needs.',
    career: 'Libra excels in careers that involve diplomacy, justice, and aesthetics. They make excellent lawyers, judges, mediators, fashion designers, and art directors. Their ability to see all sides of an issue makes them valuable in conflict resolution. They thrive in harmonious work environments.',
    health: 'Libra rules the kidneys and lower back. They may be prone to kidney issues and lower back pain. Balancing work and rest is crucial for their health. Regular exercise, particularly activities that promote balance like yoga and tai chi, benefit them greatly. Staying hydrated is especially important.',
  },
  scorpio: {
    name: 'Scorpio',
    slug: 'scorpio',
    symbol: '♏',
    emoji: '🦂',
    dates: { tropical: 'October 23 – November 21', sidereal: 'November 16 – December 15' },
    element: 'Water',
    planet: 'Pluto',
    quality: 'Fixed',
    color: '#8B0000',
    stone: 'Topaz',
    luckyNumbers: [8, 11, 18],
    luckyDay: 'Tuesday',
    compatibility: ['cancer', 'pisces', 'virgo', 'capricorn'],
    traits: {
      positive: ['Resourceful', 'Brave', 'Passionate', 'Stubborn', 'True Friend', 'Focused', 'Powerful'],
      negative: ['Distrusting', 'Jealous', 'Secretive', 'Violent', 'Controlling'],
    },
    description: 'Scorpio is a water sign ruled by Pluto, the planet of transformation. The most mysterious and intense sign of the zodiac, Scorpios are known for their magnetic personalities and depth of emotion. They possess an extraordinary ability to understand the hidden depths of human nature. Transformation is Scorpio\'s superpower — they rise from the ashes stronger each time.',
    love: 'In love, Scorpio is intensely passionate, deeply committed, and fiercely protective. They love with their whole being and expect the same in return. Trust is paramount — once broken, it is nearly impossible to regain. They are drawn to powerful connections that transform both partners on a soul level.',
    career: 'Scorpio excels in careers that involve investigation, transformation, and power. They make excellent detectives, surgeons, psychologists, researchers, and financial advisors. Their ability to uncover hidden truths and their unwavering focus make them formidable in any competitive field.',
    health: 'Scorpio rules the reproductive system and excretory organs. They may be prone to issues in these areas. Their intense emotional nature can lead to psychosomatic conditions. Regular detoxification practices and emotional release through therapy or creative outlets are beneficial. Water activities help soothe their intense energy.',
  },
  sagittarius: {
    name: 'Sagittarius',
    slug: 'sagittarius',
    symbol: '♐',
    emoji: '🏹',
    dates: { tropical: 'November 22 – December 21', sidereal: 'December 16 – January 14' },
    element: 'Fire',
    planet: 'Jupiter',
    quality: 'Mutable',
    color: '#9400D3',
    stone: 'Turquoise',
    luckyNumbers: [6, 9, 12],
    luckyDay: 'Thursday',
    compatibility: ['aries', 'leo', 'libra', 'aquarius'],
    traits: {
      positive: ['Generous', 'Idealistic', 'Great sense of humor', 'Philosophical', 'Adventurous', 'Enthusiastic'],
      negative: ['Promises more than can deliver', 'Very impatient', 'Will say anything', 'Lack of tact'],
    },
    description: 'Sagittarius, the archer, is ruled by Jupiter, the planet of expansion and abundance. The most optimistic and adventurous sign of the zodiac, Sagittarians are eternal seekers of truth and wisdom. They have an insatiable thirst for knowledge, experience, and freedom. Their philosophical mind is always questioning, always seeking to understand the greater meaning of life.',
    love: 'In love, Sagittarius is free-spirited, fun, and philosophical. They need a partner who shares their love of adventure and intellectual exploration. They resist anything that feels like a cage, so they need space and freedom in relationships. When they commit, they bring joy, optimism, and endless adventures to the partnership.',
    career: 'Sagittarius thrives in careers that offer freedom, travel, and intellectual stimulation. They excel as professors, travel writers, international business people, philosophers, and comedians. Their broad worldview and optimism make them natural entrepreneurs. They dislike routine and need variety in their work.',
    health: 'Sagittarius rules the hips, thighs, and liver. They may be prone to hip and thigh injuries, particularly from sports. Their love of excess can stress the liver. Regular outdoor exercise, particularly running and hiking, suits their adventurous nature. Moderation in food and drink is important for their wellbeing.',
  },
  capricorn: {
    name: 'Capricorn',
    slug: 'capricorn',
    symbol: '♑',
    emoji: '🐐',
    dates: { tropical: 'December 22 – January 19', sidereal: 'January 15 – February 12' },
    element: 'Earth',
    planet: 'Saturn',
    quality: 'Cardinal',
    color: '#556B2F',
    stone: 'Garnet',
    luckyNumbers: [4, 8, 13],
    luckyDay: 'Saturday',
    compatibility: ['taurus', 'virgo', 'scorpio', 'pisces'],
    traits: {
      positive: ['Responsible', 'Disciplined', 'Self-control', 'Good managers', 'Ambitious', 'Persistent', 'Practical'],
      negative: ['Know-it-all', 'Unforgiving', 'Condescending', 'Expecting the worst', 'Pessimistic'],
    },
    description: 'Capricorn is an earth sign ruled by Saturn, the planet of discipline and structure. The most ambitious sign of the zodiac, Capricorns are driven by an almost supernatural desire to succeed. They combine practicality with ambition, climbing steadily toward their goals with patient determination. Like the mountain goat they represent, they can navigate the steepest terrain.',
    love: 'In love, Capricorn is loyal, committed, and takes relationships seriously. They are slow to open up but once they do, they are devoted partners. They show love through acts of service and by providing stability and security. They seek partners who are equally ambitious and can appreciate their steady, dependable nature.',
    career: 'Capricorn excels in traditional, structured careers. They make excellent executives, financial advisors, managers, architects, and engineers. Their discipline and long-term thinking make them natural leaders. They tend to reach the peak of their careers later in life but achieve lasting success. They are excellent with financial planning.',
    health: 'Capricorn rules the bones, joints, and skin. They may be prone to arthritis, joint problems, and skin conditions. Their serious nature can lead to depression if they don\'t balance work with play. Regular exercise, particularly weight-bearing activities that strengthen bones, is beneficial. Getting adequate rest is essential.',
  },
  aquarius: {
    name: 'Aquarius',
    slug: 'aquarius',
    symbol: '♒',
    emoji: '🌊',
    dates: { tropical: 'January 20 – February 18', sidereal: 'February 13 – March 14' },
    element: 'Air',
    planet: 'Uranus',
    quality: 'Fixed',
    color: '#00CED1',
    stone: 'Amethyst',
    luckyNumbers: [4, 7, 11],
    luckyDay: 'Saturday',
    compatibility: ['gemini', 'libra', 'aries', 'sagittarius'],
    traits: {
      positive: ['Progressive', 'Original', 'Independent', 'Humanitarian', 'Innovative', 'Intellectual', 'Visionary'],
      negative: ['Runs from emotional expression', 'Temperamental', 'Uncompromising', 'Aloof', 'Detached'],
    },
    description: 'Aquarius is an air sign ruled by Uranus, the planet of rebellion and revolution. The water-bearer of the zodiac, Aquarians are visionary humanitarians dedicated to making the world a better place. They are ahead of their time, always embracing new ideas and technologies. Aquarius is the most progressive and forward-thinking sign, often seen as eccentric or revolutionary by others.',
    love: 'In love, Aquarius is unconventional, intellectually stimulating, and fiercely independent. They need a partner who can be both a lover and a best friend. They resist being controlled or losing their independence. When committed, they are loyal and genuinely interested in their partner\'s growth and wellbeing.',
    career: 'Aquarius excels in careers that allow them to innovate and help humanity. They make excellent scientists, inventors, social workers, activists, and technology pioneers. Their unique perspective and ability to think outside the box make them valuable in any forward-thinking organization. They thrive in collaborative environments.',
    health: 'Aquarius rules the circulatory system, ankles, and calves. They may be prone to circulatory disorders and ankle injuries. Their unconventional lifestyles can sometimes lead to irregular health habits. They benefit from group activities and social exercise like team sports. Keeping a consistent sleep schedule helps regulate their system.',
  },
  pisces: {
    name: 'Pisces',
    slug: 'pisces',
    symbol: '♓',
    emoji: '🐟',
    dates: { tropical: 'February 19 – March 20', sidereal: 'March 15 – April 14' },
    element: 'Water',
    planet: 'Neptune',
    quality: 'Mutable',
    color: '#008080',
    stone: 'Aquamarine',
    luckyNumbers: [3, 9, 12],
    luckyDay: 'Thursday',
    compatibility: ['cancer', 'scorpio', 'taurus', 'capricorn'],
    traits: {
      positive: ['Compassionate', 'Artistic', 'Intuitive', 'Gentle', 'Wise', 'Musical', 'Empathetic'],
      negative: ['Fearful', 'Overly trusting', 'Sad', 'Desire to escape reality', 'Can be victim/martyr'],
    },
    description: 'Pisces is a water sign ruled by Neptune, the planet of dreams, intuition, and spiritual realms. The final sign of the zodiac, Pisces has absorbed all the lessons of the other eleven signs. They are the most empathetic and spiritually connected of all signs. Their imagination knows no bounds, and they often blur the line between fantasy and reality.',
    love: 'In love, Pisces is romantic, dreamy, and unconditionally giving. They love with complete abandon and can sometimes lose themselves in a relationship. They are deeply intuitive about their partner\'s needs and incredibly supportive. They need a partner who can appreciate their sensitivity and protect their gentle heart.',
    career: 'Pisces excels in creative and healing careers. They make excellent artists, musicians, actors, healers, and spiritual counselors. Their deep empathy makes them natural therapists. They thrive in careers where they can use their imagination and help others. They should be wary of workplace environments that are overly competitive or materialistic.',
    health: 'Pisces rules the feet and immune system. They may be prone to foot problems and immune disorders. Their sensitive nature makes them susceptible to absorbing others\' negative energy. Regular spiritual practices like meditation and time near water are essential. They should be mindful of tendencies toward escapism, including substance use.',
  },
}

export const getAllSigns = () => Object.values(zodiacData)
export const getSignBySlug = (slug) => zodiacData[slug] || null
export const getAllSlugs = () => Object.keys(zodiacData)

export default zodiacData
